services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: farm-app
    ports:
      - "8000:8080"
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: ${APP_KEY:-base64:somekey}
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE:-farm_db}
      DB_USERNAME: ${DB_USERNAME:-sail}
      DB_PASSWORD: ${DB_PASSWORD:-password}
    depends_on:
      - mysql
    networks:
      - farm-network

  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-password}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE:-farm_db}'
      MYSQL_USER: '${DB_USERNAME:-sail}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-password}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    networks:
      - farm-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s

networks:
  farm-network:
    driver: bridge
